version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=9^khx6m_1*!&r2()pf7%398f_6vz*_e3^hu)5c(w6h7xr1w4dk"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
    postgres_data: